pipeline {
  agent any
  environment {
    DOCKERHUB_CREDENTIALS = credentials('DockerHub')
  }
  stages {
    // stage('Git Checkout') {
    //   steps {
    //     git 'https://github.com/przemekgorzynski/jenkins.git'
    //   }
    // }
    stage('Docker Install') {
      steps{
        sh ' curl -fsSL https://get.docker.com -o get-docker.sh | sh'
        }
    }
    stage('Docker Build') {
      steps {
        sh 'docker build -t pgorzynski/gorillabay:latest .'
      }
    }
  }
//   post {
//     always {
//       sh 'docker logout'
//     }
//   }
}