//   post {
//     always {
//       sh 'docker logout'
//     }
//   }

pipeline {
    environment {
        registry = "pgorzynski/gorillabay"
        registryCredential = 'DockerHub'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Cloning our Git') {
            steps {
                git 'https://github.com/przemekgorzynski/jenkins.git'
            }
        }
        stage('Building our image') {
            steps{
                dir('webpage'){
                    script {
                        dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    }
                }
                sh 'docker images'
            }
        }
        // stage('Deploy our image') {
        //     steps{
        //         script {
        //             docker.withRegistry( '', registryCredential ) 
        //             {
        //             dockerImage.push()
        //             }
        //         }
        //     }
        // }
        // stage('Cleaning up') {
        //     steps{
        //         sh "docker rmi $registry:$BUILD_NUMBER"
        //     }
        // }
    }
}