pipeline {
    environment {
        registry = "pgorzynski/gorillabay-webpage"
        registryCredential = 'DockerHub'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Clone Git') {
            steps {
                git 'https://github.com/przemekgorzynski/jenkins.git'
            }
        }
        stage('Build docker image') {
            steps{
                dir('webpage'){
                    script {
                        dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    }
                }
                sh 'docker images'
            }
        }
        stage('Push image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) 
                    {
                    dockerImage.push()
                    }
                }
            }
        }
        stage('Clean up image') {
            steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
                sh 'docker images'
            }
        }
    }
}